package com.jmc.scm.system.model;

import java.util.HashMap;
import java.util.Map;

import org.springframework.beans.factory.InitializingBean;

public class ContentType implements InitializingBean {

	private static final Map<String, String> contentType = new HashMap<String, String>();

	public static String getContentTypeByFileType(String fileType) {
		String result = contentType.get(fileType);
		if (result == null) {
			result = contentType.get(".*");
		}
		return result;
	}

	@Override
	public void afterPropertiesSet() throws Exception {
		contentType.put(".*", "application/octet-stream");
		contentType.put("0.001", "application/x-001");
		contentType.put("0.323", "text/h323");
		contentType.put("0.907", "drawing/907");
		contentType.put(".acp", "audio/x-mei-aac");
		contentType.put(".aif", "audio/aiff");
		contentType.put(".aiff", "audio/aiff");
		contentType.put(".asa", "text/asa");
		contentType.put(".asp", "text/asp");
		contentType.put(".au", "audio/basic");
		contentType.put(".awf", "application/vnd.adobe.workflow");
		contentType.put(".bmp", "application/x-bmp");
		contentType.put(".c4t", "application/x-c4t");
		contentType.put(".cal", "application/x-cals");
		contentType.put(".cdf", "application/x-netcdf");
		contentType.put(".cel", "application/x-cel");
		contentType.put(".cg4", "application/x-g4");
		contentType.put(".cit", "application/x-cit");
		contentType.put(".cml", "text/xml");
		contentType.put(".cmx", "application/x-cmx");
		contentType.put(".crl", "application/pkix-crl");
		contentType.put(".csi", "application/x-csi");
		contentType.put(".cut", "application/x-cut");
		contentType.put(".dbm", "application/x-dbm");
		contentType.put(".dcd", "text/xml");
		contentType.put(".der", "application/x-x509-ca-cert");
		contentType.put(".dib", "application/x-dib");
		contentType.put(".doc", "application/msword");
		contentType.put(".drw", "application/x-drw");
		contentType.put(".dwf", "Model/vnd.dwf");
		contentType.put(".dwg", "application/x-dwg");
		contentType.put(".dxf", "application/x-dxf");
		contentType.put(".emf", "application/x-emf");
		contentType.put(".ent", "text/xml");
		contentType.put(".eps", "application/x-ps");
		contentType.put(".etd", "application/x-ebx");
		contentType.put(".fax", "image/fax");
		contentType.put(".fif", "application/fractals");
		contentType.put(".frm", "application/x-frm");
		contentType.put(".gbr", "application/x-gbr");
		contentType.put(".gif", "image/gif");
		contentType.put(".gp4", "application/x-gp4");
		contentType.put(".hmr", "application/x-hmr");
		contentType.put(".hpl", "application/x-hpl");
		contentType.put(".hrf", "application/x-hrf");
		contentType.put(".htc", "text/x-component");
		contentType.put(".html", "text/html");
		contentType.put(".htx", "text/html");
		contentType.put(".ico", "image/x-icon");
		contentType.put(".iff", "application/x-iff");
		contentType.put(".igs", "application/x-igs");
		contentType.put(".img", "application/x-img");
		contentType.put(".isp", "application/x-internet-signup");
		contentType.put(".java", "java/*");
		contentType.put(".jpe", "image/jpeg");
		contentType.put(".jpeg", "image/jpeg");
		contentType.put(".jpg", "image/jpeg");
//		contentType.put(".jpg", "application/x-jpg");
		contentType.put(".jsp", "text/html");
		contentType.put(".lar", "application/x-laplayer-reg");
		contentType.put(".lavs", "audio/x-liquid-secure");
		contentType.put(".lmsff", "audio/x-la-lms");
		contentType.put(".ltr", "application/x-ltr");
		contentType.put(".m2v", "video/x-mpeg");
		contentType.put(".m4e", "video/mpeg4");
		contentType.put(".man", "application/x-troff-man");
		contentType.put(".mdb", "application/msaccess");
		contentType.put(".mfp", "application/x-shockwave-flash");
		contentType.put(".mhtml", "message/rfc822");
		contentType.put(".mid", "audio/mid");
		contentType.put(".mil", "application/x-mil");
		contentType.put(".mnd", "audio/x-musicnet-download");
		contentType.put(".mocha", "application/x-javascript");
		contentType.put(".mp1", "audio/mp1");
		contentType.put(".mp2v", "video/mpeg");
		contentType.put(".mp4", "video/mpeg4");
		contentType.put(".mpd", "application/vnd.ms-project");
		contentType.put(".mpeg", "video/mpg");
		contentType.put(".mpga", "audio/rn-mpeg");
		contentType.put(".mps", "video/x-mpeg");
		contentType.put(".mpv", "video/mpg");
		contentType.put(".mpw", "application/vnd.ms-project");
		contentType.put(".mtx", "text/xml");
		contentType.put(".net", "image/pnetvue");
		contentType.put(".nws", "message/rfc822");
		contentType.put(".out", "application/x-out");
		contentType.put(".p12", "application/x-pkcs12");
		contentType.put(".p7c", "application/pkcs7-mime");
		contentType.put(".p7r", "application/x-pkcs7-certreqresp");
		contentType.put(".pc5", "application/x-pc5");
		contentType.put(".pcl", "application/x-pcl");
		contentType.put(".pdf", "application/pdf");
		contentType.put(".pdx", "application/vnd.adobe.pdx");
		contentType.put(".pgl", "application/x-pgl");
		contentType.put(".pko", "application/vnd.ms-pki.pko");
		contentType.put(".plg", "text/html");
		contentType.put(".plt", "application/x-plt");
		contentType.put(".png", "application/x-png");
		contentType.put(".ppa", "application/vnd.ms-powerpoint");
		contentType.put(".pps", "application/vnd.ms-powerpoint");
		contentType.put(".ppt", "application/x-ppt");
		contentType.put(".prf", "application/pics-rules");
		contentType.put(".prt", "application/x-prt");
		contentType.put(".ps", "application/postscript");
		contentType.put(".pwz", "application/vnd.ms-powerpoint");
		contentType.put(".ra", "audio/vnd.rn-realaudio");
		contentType.put(".ras", "application/x-ras");
		contentType.put(".rdf", "text/xml");
		contentType.put(".red", "application/x-red");
		contentType.put(".rjs", "application/vnd.rn-realsystem-rjs");
		contentType.put(".rlc", "application/x-rlc");
		contentType.put(".rm", "application/vnd.rn-realmedia");
		contentType.put(".rmi", "audio/mid");
		contentType.put(".rmm", "audio/x-pn-realaudio");
		contentType.put(".rms", "application/vnd.rn-realmedia-secure");
		contentType.put(".rmx", "application/vnd.rn-realsystem-rmx");
		contentType.put(".rp", "image/vnd.rn-realpix");
		contentType.put(".rsml", "application/vnd.rn-rsml");
		contentType.put(".rtf", "application/msword");
		contentType.put(".rv", "video/vnd.rn-realvideo");
		contentType.put(".sat", "application/x-sat");
		contentType.put(".sdw", "application/x-sdw");
		contentType.put(".slb", "application/x-slb");
		contentType.put(".slk", "drawing/x-slk");
		contentType.put(".smil", "application/smil");
		contentType.put(".snd", "audio/basic");
		contentType.put(".sor", "text/plain");
		contentType.put(".spl", "application/futuresplash");
		contentType.put(".ssm", "application/streamingmedia");
		contentType.put(".stl", "application/vnd.ms-pki.stl");
		contentType.put(".sty", "application/x-sty");
		contentType.put(".swf", "application/x-shockwave-flash");
		contentType.put(".tg4", "application/x-tg4");
		contentType.put(".tif", "image/tiff");
		contentType.put(".tiff", "image/tiff");
		contentType.put(".top", "drawing/x-top");
		contentType.put(".tsd", "text/xml");
		contentType.put(".uin", "application/x-icq");
		contentType.put(".vcf", "text/x-vcard");
		contentType.put(".vdx", "application/vnd.visio");
		contentType.put(".vpg", "application/x-vpeg005");
		contentType.put(".vsd", "application/x-vsd");
		contentType.put(".vst", "application/vnd.visio");
		contentType.put(".vsw", "application/vnd.visio");
		contentType.put(".vtx", "application/vnd.visio");
		contentType.put(".wav", "audio/wav");
		contentType.put(".wb1", "application/x-wb1");
		contentType.put(".wb3", "application/x-wb3");
		contentType.put(".wiz", "application/msword");
		contentType.put(".wk4", "application/x-wk4");
		contentType.put(".wks", "application/x-wks");
		contentType.put(".wma", "audio/x-ms-wma");
		contentType.put(".wmf", "application/x-wmf");
		contentType.put(".wmv", "video/x-ms-wmv");
		contentType.put(".wmz", "application/x-ms-wmz");
		contentType.put(".wpd", "application/x-wpd");
		contentType.put(".wpl", "application/vnd.ms-wpl");
		contentType.put(".wr1", "application/x-wr1");
		contentType.put(".wrk", "application/x-wrk");
		contentType.put(".ws2", "application/x-ws");
		contentType.put(".wsdl", "text/xml");
		contentType.put(".xdp", "application/vnd.adobe.xdp");
		contentType.put(".xfd", "application/vnd.adobe.xfd");
		contentType.put(".xhtml", "text/html");
		contentType.put(".xls", "application/x-xls");
		contentType.put(".xml", "text/xml");
		contentType.put(".xq", "text/xml");
		contentType.put(".xquery", "text/xml");
		contentType.put(".xsl", "text/xml");
		contentType.put(".xwd", "application/x-xwd");
		contentType.put(".sis", "application/vnd.symbian.install");
		contentType.put(".x_t", "application/x-x_t");
		contentType.put(".apk", "application/vnd.android.package-archive");

	}

}
